version: '2'
services:
  node1:
    build:
      context: ./
      dockerfile: Dockerfile-alternate
    ports:
      - "6000:6000"
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ~/github/rethink-blockchain:/rethink-blockchain
  node2:
    build:
      context: ./
      dockerfile: Dockerfile-alternate
    ports:
      - "6001:6000"
      - "3001:3000"
      - "8081:8080"
    volumes:
      - ~/github/rethink-blockchain:/rethink-blockchain